services:
  app:
    container_name: mood2mix-application
    restart: always
    build: .
    command: "poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
